name: Build

env:
  JAVA_OPTS: "-Xms512m -Xmx6048m -Xss128m -XX:ReservedCodeCacheSize=512m -server -XX:+UseG1GC"
  GRADLE_OPTS: "-Xms512m -Xmx6048m -Xss128m -XX:ReservedCodeCacheSize=512m -server -XX:+UseG1GC"
  TERM: xterm-256color
  JDK_CURRENT: 11.0.10
  JDK_LATEST: 15
  CI: "true" # scripts use this and run CAS/Strapi in background.

##########################################################################

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

##########################################################################

jobs:
            
##########################################################################

  test:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    continue-on-error: false
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JDK_CURRENT }}
      - uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: "Clone Strapi"
        shell: "bash" 
        run: ./clone-strapi.sh
      - uses: actions/cache@v2
        with:
          path: |
            strapi/node_modules
            puppeteer/node_modules
            strapi/examples/getstarted/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: "Start CAS"
        shell: "bash" 
        run: ./run-cas.sh
      - name: "Start Strapi"
        shell: "bash" 
        run: ./run-strapi.sh
      - name: "Register Admin"
        shell: "bash" 
        run: ./register_strapi_admin.sh | jq .
      - name: "Run puppeteer test"
        shell: "bash" 
        run: |
          cd puppeteer
          ./run.sh
          grep \"jwt\" testoutput.log | tail -1 | jq .
      - uses: actions/upload-artifact@v2
        if: ${{ matrix.os == 'ubuntu-latest' }}
        with:
          name: cas-server
          path: |
            ./cas-server/**
            !./cas-server/.gradle
            !./cas-server/build/overlays
            !./cas-server/build/generated
            !./cas-server/build/classes
            !./cas-server/build/resources
            !./cas-server/build/tomcat
            !./cas-server/build/tmp
      - uses: actions/upload-artifact@v2
        if: ${{ matrix.os == 'ubuntu-latest' }}
        with:
          name: strapi-example
          path: |
            ./strapi/examples/getstarted/**
            !./strapi/examples/getstarted/node_modules
      - uses: actions/upload-artifact@v2
        if: ${{ matrix.os == 'ubuntu-latest' }}
        with:
          name: puppeteer-screenshots
          path: ./puppeteer/*.png
