name: Build

env:
  JAVA_OPTS: "-Xms512m -Xmx6048m -Xss128m -XX:ReservedCodeCacheSize=512m -server -XX:+UseG1GC"
  GRADLE_OPTS: "-Xms512m -Xmx6048m -Xss128m -XX:ReservedCodeCacheSize=512m -server -XX:+UseG1GC"
  TERM: xterm-256color
  JDK_CURRENT: 11.0.10
  JDK_LATEST: 15
  CI: "true" # scripts use this and run CAS/Strapi in background.

##########################################################################

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

##########################################################################

jobs:
            
##########################################################################

  test:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    continue-on-error: false
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JDK_CURRENT }}
      - uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: "Start CAS and Strapi"
        shell: "bash" 
        run: |
          ./run-cas.sh
          ./run-strapi.sh
          ./register_strapi_admin.sh | jq .
      - uses: actions/upload-artifact@v2
        if: ${{ matrix.os == 'ubuntu-latest' }}
        with:
          name: cas-server
          path: ./cas-server/**
      - uses: actions/upload-artifact@v2
        if: ${{ matrix.os == 'ubuntu-latest' }}
        with:
          name: strapi-example
          path: ./strapi/examples/getstarted/**
