name: Build

env:
  JAVA_OPTS: "-Xms512m -Xmx6048m -Xss128m -XX:ReservedCodeCacheSize=512m -server -XX:+UseG1GC"
  GRADLE_OPTS: "-Xms512m -Xmx6048m -Xss128m -XX:ReservedCodeCacheSize=512m -server -XX:+UseG1GC"
  TERM: xterm-256color
  JDK_CURRENT: 11.0.10
  JDK_LATEST: 15

##########################################################################

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

##########################################################################

jobs:
            
##########################################################################

  test:
    continue-on-error: false
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    shell: "bash" 
    steps:
      - name:
        run: |
          'run-cas.sh &'
          'sleep 180'
          'run-starpi.sh &'
          'sleep 180'
