name: Build

env:
  JAVA_OPTS: "-Xms512m -Xmx6048m -Xss128m -XX:ReservedCodeCacheSize=512m -server -XX:+UseG1GC"
  GRADLE_OPTS: "-Xms512m -Xmx6048m -Xss128m -XX:ReservedCodeCacheSize=512m -server -XX:+UseG1GC"
  TERM: xterm-256color
  JDK_CURRENT: 11.0.10
  JDK_LATEST: 15
  CI: "true" # scripts use this and run CAS/Strapi in background.

##########################################################################

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

##########################################################################

jobs:
            
##########################################################################

  test:
    continue-on-error: false
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JDK_CURRENT }}        
      - name: "Start CAS and Strapi"
        shell: "bash" 
        run: |
          ./run-cas.sh
          ./run-strapi.sh 
